development:
  adapter: postgresql
  database: nate_database
  username:
  host: localhost

test:
  adapter: postgresql
  database: nate_database
  username:
  host: localhost

production:
  adapter: postgresql
  database: nate_database
  username:
