development:
  bucket: nate_database
  access_key_id: AKIAJYO6ALTV3O5SMVXA
  secret_access_key: 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
test:
  bucket: nate_database
  access_key_id: AKIAJYO6ALTV3O5SMVXA
  secret_access_key: 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
production:
  bucket: nate_database
  access_key_id: AKIAJYO6ALTV3O5SMVXA
  secret_access_key: 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
