development:
  bucket: nate_database
  access_key_id: AKIAIAJ4LNKEMBNRH26Q
  secret_access_key: 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
test:
  bucket: nate_database
  access_key_id: AKIAIAJ4LNKEMBNRH26Q
  secret_access_key: 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
production:
  bucket: nate_database
  access_key_id: AKIAIAJ4LNKEMBNRH26Q
  secret_access_key: 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
